language: ruby
rvm:
- 2.3.3

script: ./script/ci:build

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: nickmeldrum-com-blog
  skip_cleanup: true
  local_dir: _site
  region: $AWS_DEFAULT_REGION

sudo: false
